#!/usr/bin/env bash

if [ -z "${wdir}" ]; then wdir="./"; fi;
git -C ${wdir} pull
ROLE=podman
# on startup, each container is assigned a single IP address beginning 10.*, which without configured forwarding is accessible only on the host machine
hostname -I > ${wdir}${ROLE}
git -C $wdir add ${ROLE}
git -C $wdir commit -m "${ROLE} IP updated"
git -C $wdir push origin master
