#!/usr/bin/env bash
git pull
ROLE=podman
# on startup, each container is assigned a single IP address beginning 10.*, which without configured forwarding is accessible only on the host machine
hostname -I > ${ROLE}
git add ${ROLE}
git commit -m "${ROLE} IP updated"
git push origin master
